### ISSUE TITLE
Command: `gm hermes keys` failed

### ISSUE THREAD

**Issue by ImJeremyHe** [informalsystems/gm#2]
## Summary of Bug
https://hermes.informal.systems/tutorials/local-chains/start.html
It is said that `gm hermes keys` would automatically generate private keys.
```
gm hermes keys
echo $?
1
```
But it failed without any message.

## Version
```
gm version
v0.1.3
```

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by harveenSingh** [comment]
Thank you for pointing this out. @ImJeremyHe @adizere 
I will work on making the changes

**Comment by greg-szabo** [comment]
Fixed in v0.1.4 release. Thanks for reporting it!
