### ISSUE TITLE
Command `gm start` fails with mysterious error `failed to parse global label number 0`

### ISSUE THREAD

**Issue by adizere** [informalsystems/gm#4]
Steps to reproduce:

- fresh installation of MacOS / zsh 5.8.1 (x86_64-apple-darwin22.0)
- fresh installation of Hermes and `gm v0.1.3`
- fresh installation of gaiad
    - tried with v5*, v7* and `main`
    - also tried with `simd` from `ibc-go`
    - same problem occurs with all of them

Error:

```bash
% gm start
ibc-0 started, PID: 72474, LOG: /Users/adiseredinschi/.gm/ibc-0/log
WARNING: ibc-0 failed. Check the logs with `gm log ibc-0`.

% gm log ibc-0

Error: failed to parse global label number 0 from config
Usage:
  gaiad start [flags]
```

The error `failed to parse global label number 0 from config` is extremely ambiguous. That's gaia/SDK fault. After digging for a while turns out the problem is the telemetry section of `config/app.toml` for chain ibc-0. Specifically this section in `app.toml`:

```toml
[telemetry]
# ...
global-labels = ['panic', 'gaiad']
# ...
```

It seems like `gm` has a specific workaround that produces the `global-labels` line:

https://github.com/informalsystems/gm/blob/b3bc17d88e50076f8c9a954a437454605cc42e84/bin/lib-gm#L662-L665

I don't understand the reason for the `sconfig` and `sed` commands. The vanilla `app.toml` produced with `gaia init` has

```toml
global-labels = [
]
```

Which does not trigger any error. So it's unclear why the workaround should exist in the first place.

**Comment by adizere** [comment]
I'm sure I'm missing something and removing the "Workaround" lines will eventually break something, but my hot fix is as follows:


```diff
% git diff
diff --git a/bin/lib-gm b/bin/lib-gm
index c866ced..73cfe32 100644
--- a/bin/lib-gm
+++ b/bin/lib-gm
@@ -659,10 +659,6 @@ configure() {
   sconfig "$HOME_DIR/config/config.toml" "p2p.laddr=tcp://0.0.0.0:${P2P}" 1> /dev/null
   sconfig "$HOME_DIR/config/config.toml" "rpc.laddr=tcp://0.0.0.0:${RPC}" 1> /dev/null
   sconfig "$HOME_DIR/config/config.toml" "rpc.pprof_laddr=0.0.0.0:${PPROF}" 1> /dev/null
-  # Workaround for https://github.com/spf13/viper/issues/1132
-  #   Viper does not support writing array of arrays so we clean out the variable
-  sconfig "$HOME_DIR/config/app.toml" -t stringSlice "telemetry.global-labels=panic gaiad" 1> /dev/null
-  sed -i.bak 's/  global-labels = \["panic","gaiad"\]/  global-labels = []/' "$HOME_DIR/config/app.toml"
   # End of workaround
   sconfig "$HOME_DIR/config/app.toml" "api.address=tcp://0.0.0.0:${APP}" 1> /dev/null
   sconfig "$HOME_DIR/config/app.toml" "api.enable=true" 1> /dev/null
```

**Comment by greg-szabo** [comment]
The workaround was implemented because of the issue described in https://github.com/spf13/viper/issues/1132 that affected sconfig. Since then, new versions of viper were released that apparently fixed that issue. Only I wasn't aware of that since they didn't upgrade the issue. The current version of sconfig is already built with a version of viper that has the fix, so this workaround can be removed.

Removed in v0.1.4 release

**Comment by adizere** [comment]
Thanks Greg!
