### ISSUE TITLE
support simultaneously binaries with/without `genesis` sub-command

### ISSUE THREAD

**Issue by crodriguezvega** [informalsystems/gm#7]
Since Cosmos SDK v0.47 the genesis commands have all been grouped under a `genesis` top level sub-command. See [issue](https://github.com/cosmos/cosmos-sdk/issues/14130) and [PR](https://github.com/cosmos/cosmos-sdk/pull/14149) in Cosmos SDK repository.

It would be nice if `gm` could differentiate whether the chain binary has the genesis commands in the top level directly or under the `genesis` sub-command.

**Comment by greg-szabo** [comment]
Oh, you guys and your CLI rearrangements. :D

Great point, thanks for opening the issue, Carlos. Most probably we'll do some kind of "fallback" implementation (as we did with the tendermint sub-command before). Unfortunately, we ran into network binaries that removed the `--long` parameter from the `version` command, hence it's not always trivial to query the SDK version used in the binary. (Injective, I'm looking at you...)

If you could strongly encourage downstream developers to keep the flags the core teams provide, please apply the pressure. ;)

**Comment by greg-szabo** [comment]
Fixed in #8 .
